//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreateIT.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-612URIC1ADU;Initial Catalog=K5_DEVELOPER;User Id=K5developersql;P" +
            "assword=K5o126473developer;")]
        public string SQLConnStringLive {
            get {
                return ((string)(this["SQLConnStringLive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ORACLESERVER\\SQL2008DEV;Initial Catalog=K5_ENVIRONTEC_BE;User ID=sa;P" +
            "assword=D3lt@net")]
        public string SQLConnStringTest {
            get {
                return ((string)(this["SQLConnStringTest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-A6IVLFBUBP2;Initial Catalog=K5_ENVIRONTEC_BE_test;User Id=environ" +
            "tecsql;Password=environ9986435677tec;")]
        public string SQLConnStringEnvirontecTest {
            get {
                return ((string)(this["SQLConnStringEnvirontecTest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-A6IVLFBUBP2;Initial Catalog=K5_ENVIRONTEC_BE;User Id=environtecsq" +
            "l;Password=environ9986435677tec;")]
        public string SQLConnStringEnvirontecLive {
            get {
                return ((string)(this["SQLConnStringEnvirontecLive"]));
            }
        }
    }
}
